### ISSUE TITLE
Update to butane 0.6

### ISSUE THREAD

**Issue by jayvdb** [DimmKG/butane_rocket_pool#1]
butane 0.6 has been out for a while.

It would be helpful to know if this project works with butane 0.6, and also if butane `main` also works, so we can make any needed adjustments to butane before the 0.7 release.

**Comment by DimmKG** [comment]
Currently, library works with the latest versions of Butane 5.1 and rocket 0.5.0-rc3.
I have added example app to check.

Now I am checking compatibility between repo version of Butane

I cannot find any mentions of new butane versions 0.6. Where can I find it?

**Comment by DimmKG** [comment]
Example app also works with Butane from [`master` branch](https://github.com/Electron100/butane), but only inside library workspace. Maybe I need to update butane  dependency version in future.

**Comment by jayvdb** [comment]
Ah sorry, yes 0.6 is the next release.

Thanks for adding an example, and keeping on maintaining this.
